create table "user"(
    id int generated by default as identity primary key,
    full_name varchar(75) not null,
    password varchar not null,
    birthdate date not null
);

create table account(
    id int generated by default as identity primary key,
    user_id int references "user"(id) unique not null,
    count float not null check ( count >= 0 )
);

create table email(
    id int generated by default as identity primary key,
    user_id int references "user"(id) unique not null,
    value varchar not null unique
);

create table phone_number(
    id int generated by default as identity primary key,
    user_id int references "user"(id) unique not null,
    value varchar not null unique
);